# -*- coding: utf-8 -*-
"""Mamba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o961k7sQp0QwXnBnKsgiTNERod8om0YI
"""

from google.colab import drive

drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi
!pip install -U pip setuptools wheel packaging ninja
!pip install mamba-ssm --no-build-isolation

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/state-spaces/mamba.git
# %cd /content/mamba
!ls

#Environment Check
import torch
from mamba_ssm import Mamba

print(torch.__version__)
print(torch.cuda.is_available())

x = torch.randn(2, 64, 16).cuda()
model = Mamba(d_model=16, d_state=16, d_conv=4, expand=2,).cuda()

y = model(x)
print(y.shape)

ls

"""**Dataset Download and Preprocess**"""

from datasets import load_dataset
from transformers import AutoTokenizer

dataset = load_dataset("pubmed_qa", "pqa_artificial")

def get_text(example):
    return {"text": example["question"] + " " + example["long_answer"]}

dataset = dataset.map(get_text, remove_columns=dataset["train"].column_names)
dataset = dataset["train"].train_test_split(test_size=0.1)

tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")
tokenizer.pad_token = tokenizer.eos_token

dataset.save_to_disk("/content/custom_dataset")
print("✅ dataset ready")

"""**Claim 1: By comparing with baseline, Mamba have a greater advantage in a long sequence (256, 512, 1024, 2048…)**"""

!python benchmarks/benchmark_generation_mamba_simple.py \
--model-name "state-spaces/mamba-130m" \
--prompt "Medical research is important for" \
--promptlen 2048 \
--batch 1 \
--genlen 128

!python benchmarks/benchmark_generation_mamba_simple.py \
--model-name "state-spaces/mamba-130m" \
--promptlen 4096 \
--batch 1 \
--genlen 128

!python benchmarks/benchmark_generation_mamba_simple.py \
--model-name "state-spaces/mamba-130m" \
--promptlen 8192 \
--batch 1 \
--genlen 128

lengths = [512, 1024, 2048, 4096]
test_texts = dataset["test"]["text"]
def build_prompt_of_exact_len(target_len, texts, tokenizer):
    ids = []
    i = 0
    while len(ids) < target_len:
        piece = tokenizer.encode(texts[i % len(texts)], add_special_tokens=False)
        ids.extend(piece + [tokenizer.eos_token_id])
        i += 1
    ids = ids[:target_len]
    return tokenizer.decode(ids, skip_special_tokens=False)

prompts = {L: build_prompt_of_exact_len(L, test_texts, tokenizer) for L in lengths}
for L in lengths:
    print(L, len(tokenizer.encode(prompts[L], add_special_tokens=False)))

import time
import torch
import pandas as pd
from transformers import AutoModelForCausalLM, AutoTokenizer

baseline_name = "EleutherAI/pythia-160m-deduped"

base_tokenizer = AutoTokenizer.from_pretrained(baseline_name)
if base_tokenizer.pad_token is None:
    base_tokenizer.pad_token = base_tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    baseline_name,
    torch_dtype=torch.float16
).cuda().eval()

def benchmark_transformer(model, tokenizer, prompt, genlen=128):
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    with torch.no_grad():
        _ = model.generate(
            **inputs,
            max_new_tokens=8,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    torch.cuda.synchronize()
    start = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=genlen,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    torch.cuda.synchronize()
    end = time.time()

    elapsed_ms = (end - start) * 1000
    peak_mem_mb = torch.cuda.max_memory_allocated() / (1024 ** 2)

    return elapsed_ms, peak_mem_mb

transformer_results = []

for L in lengths:
    ms, mem = benchmark_transformer(base_model, base_tokenizer, prompts[L], genlen=128)
    transformer_results.append({
        "context_length": L,
        "model": "Transformer",
        "time_ms": ms
    })

pd.DataFrame(transformer_results)

import subprocess
import re

def benchmark_mamba_script(prompt, promptlen, genlen=128):
    cmd = [
        "python",
        "benchmarks/benchmark_generation_mamba_simple.py",
        "--model-name", "state-spaces/mamba-130m",
        "--prompt", prompt,
        "--promptlen", str(promptlen),
        "--batch", "1",
        "--genlen", str(genlen)
    ]

    out = subprocess.check_output(cmd, text=True)

    match = re.search(r"time:\s*([0-9.]+)ms", out)
    if match is None:
        raise ValueError(f"Could not parse timing from output:\n{out}")

    time_ms = float(match.group(1))
    return time_ms, out


mamba_results = []
lengths = [512, 1024, 2048, 4096]
for L in lengths:
    ms, raw_output = benchmark_mamba_script(prompts[L], L, genlen=128)
    mamba_results.append({
        "context_length": L,
        "model": "Mamba",
        "time_ms": ms
    })
    print(raw_output)

df_mamba = pd.DataFrame(mamba_results)
df_mamba

timing_df = pd.DataFrame(mamba_results + transformer_results)
timing_df

"""**Claim2: Mamba-130M achieves higher average accuracy than Pythia-160M in zero-shot evaluations. Table 3(page 12)**"""

!pip install datasets transformers accelerate -q

from datasets import load_dataset

dataset = load_dataset("pubmed_qa", "pqa_artificial")
test_data = dataset["train"].select(range(200))

import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel

device = "cuda"
dtype = torch.float16

pythia_name = "EleutherAI/pythia-160m-deduped"
mamba_name = "state-spaces/mamba-130m"

pythia_tokenizer = AutoTokenizer.from_pretrained(pythia_name)
pythia_tokenizer.pad_token = pythia_tokenizer.eos_token

mamba_tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")
mamba_tokenizer.pad_token = mamba_tokenizer.eos_token

pythia_model = AutoModelForCausalLM.from_pretrained(
    pythia_name,
    torch_dtype=dtype
).to(device).eval()

mamba_model = MambaLMHeadModel.from_pretrained(
    mamba_name,
    device=device,
    dtype=dtype
).eval()

def build_pubmedqa_prompt(example):
    question = example["question"]

    context = " ".join(example["context"]["contexts"])

    prompt = (
        "Answer the biomedical question using only one word: yes, no, or maybe.\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )
    return prompt

def get_label(example):
    return example["final_decision"].strip().lower()

import torch
import torch.nn.functional as F
import pandas as pd

# 1️⃣ 构造 prompt
def build_pubmedqa_prompt(example):
    question = example["question"]
    context = " ".join(example["context"]["contexts"])

    prompt = (
        "Answer the biomedical question using only one word: yes, no, or maybe.\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )
    return prompt

# 2️⃣ 获取正确答案
def get_label(example):
    return example["final_decision"].strip().lower()

# 3️⃣ 计算一个答案的 log-prob（兼容 Mamba & Pythia）
def score_answer(model, tokenizer, prompt, answer, max_length=2048):
    full_text = prompt + answer

    enc_full = tokenizer(
        full_text,
        return_tensors="pt",
        truncation=True,
        max_length=max_length
    ).to("cuda")

    enc_prompt = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_length
    ).to("cuda")

    input_ids = enc_full["input_ids"]
    prompt_len = enc_prompt["input_ids"].shape[1]

    with torch.no_grad():
        out = model(input_ids)

    logits = out.logits if hasattr(out, "logits") else out

    # shift for causal LM
    shift_logits = logits[:, :-1, :]
    shift_labels = input_ids[:, 1:]

    # 只算 answer 部分
    answer_start = max(prompt_len - 1, 0)
    answer_logits = shift_logits[:, answer_start:, :]
    answer_labels = shift_labels[:, answer_start:]

    loss = F.cross_entropy(
        answer_logits.reshape(-1, answer_logits.size(-1)),
        answer_labels.reshape(-1),
        reduction="mean"
    )

    return -loss.item()


# 4️⃣ 预测答案（yes / no / maybe）
answer_choices = [" yes", " no", " maybe"]

def predict_answer(model, tokenizer, prompt):
    scores = {}
    for ans in answer_choices:
        scores[ans.strip()] = score_answer(model, tokenizer, prompt, ans)

    pred = max(scores, key=scores.get)
    return pred, scores


# 5️⃣ 最终 accuracy 函数（你报错的这个）
def evaluate_accuracy(model, tokenizer, data, n=200):
    correct = 0
    rows = []

    for i, ex in enumerate(data.select(range(n))):
        prompt = build_pubmedqa_prompt(ex)
        gold = get_label(ex)

        pred, scores = predict_answer(model, tokenizer, prompt)

        correct += int(pred == gold)

        rows.append({
            "idx": i,
            "gold": gold,
            "pred": pred,
            "correct": pred == gold
        })

    acc = correct / n
    return acc, pd.DataFrame(rows)

pythia_acc, pythia_acc_df = evaluate_accuracy(
    pythia_model, pythia_tokenizer, test_data, n=200
)

mamba_acc, mamba_acc_df = evaluate_accuracy(
    mamba_model, mamba_tokenizer, test_data, n=200
)

print("Pythia accuracy:", pythia_acc)
print("Mamba accuracy:", mamba_acc)

import math
import torch
import torch.nn.functional as F

def compute_lm_loss(model, input_ids):
    with torch.no_grad():
        out = model(input_ids)

    logits = out.logits if hasattr(out, "logits") else out

    # causal LM: token t predicts token t+1
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()

    loss = F.cross_entropy(
        shift_logits.view(-1, shift_logits.size(-1)),
        shift_labels.view(-1),
        reduction="mean"
    )

    return loss.item()

def build_lm_text(example):
    context = " ".join(example["context"]["contexts"])
    question = example["question"]
    answer = example["long_answer"]

    text = (
        f"Context: {context}\n"
        f"Question: {question}\n"
        f"Answer: {answer}"
    )

    return text
def evaluate_perplexity(model, tokenizer, data, n=200, max_length=2048):
    losses = []

    for ex in data.select(range(n)):
        text = build_lm_text(ex)

        enc = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=max_length
        ).to(device)

        input_ids = enc["input_ids"]

        loss = compute_lm_loss(model, input_ids)
        losses.append(loss)

    avg_loss = sum(losses) / len(losses)
    ppl = math.exp(avg_loss)

    return ppl, avg_loss

pythia_ppl, pythia_loss = evaluate_perplexity(
    pythia_model, pythia_tokenizer, test_data, n=200
)

mamba_ppl, mamba_loss = evaluate_perplexity(
    mamba_model, mamba_tokenizer, test_data, n=200
)

print("Pythia PPL:", pythia_ppl)
print("Mamba PPL:", mamba_ppl)

results = pd.DataFrame([
    {
        "model": "Pythia-160M Transformer",
        "context_length": 2048,
        "zero_shot_accuracy": pythia_acc,
        "perplexity": pythia_ppl
    },
    {
        "model": "Mamba-130M",
        "context_length": 2048,
        "zero_shot_accuracy": mamba_acc,
        "perplexity": mamba_ppl
    }
])

results

"""**Distribution Shift.**   Prompt[yes, no, maybe] -> [maybe, yes, no]"""

def build_pubmedqa_prompt_shift(example):
    question = example["question"]
    context = " ".join(example["context"]["contexts"])

    prompt = (
        "You are given a biomedical question and context.\n"
        "Choose exactly one answer from the following options: maybe, yes, no.\n\n"
        f"Scientific context: {context}\n\n"
        f"Biomedical question: {question}\n\n"
        "Final answer:"
    )
    return prompt

def evaluate_accuracy(model, tokenizer, data, n=200, prompt_fn=build_pubmedqa_prompt):
    correct = 0
    rows = []

    for i, ex in enumerate(data.select(range(n))):
        prompt = prompt_fn(ex)
        gold = get_label(ex)

        pred, scores = predict_answer(model, tokenizer, prompt)
        correct += int(pred == gold)

        rows.append({
            "idx": i,
            "gold": gold,
            "pred": pred,
            "correct": pred == gold,
            "score_yes": scores["yes"],
            "score_no": scores["no"],
            "score_maybe": scores["maybe"],
        })

    acc = correct / n
    return acc, pd.DataFrame(rows)

pythia_acc_std, _ = evaluate_accuracy(
    pythia_model, pythia_tokenizer, test_data, n=200,
    prompt_fn=build_pubmedqa_prompt
)

mamba_acc_std, _ = evaluate_accuracy(
    mamba_model, mamba_tokenizer, test_data, n=200,
    prompt_fn=build_pubmedqa_prompt
)

pythia_acc_shift, _ = evaluate_accuracy(
    pythia_model, pythia_tokenizer, test_data, n=200,
    prompt_fn=build_pubmedqa_prompt_shift
)

mamba_acc_shift, _ = evaluate_accuracy(
    mamba_model, mamba_tokenizer, test_data, n=200,
    prompt_fn=build_pubmedqa_prompt_shift
)

pd.DataFrame([
    {"model": "Pythia-160M", "setting": "standard", "accuracy": pythia_acc_std},
    {"model": "Mamba-130M", "setting": "standard", "accuracy": mamba_acc_std},
    {"model": "Pythia-160M", "setting": "prompt shift", "accuracy": pythia_acc_shift},
    {"model": "Mamba-130M", "setting": "prompt shift", "accuracy": mamba_acc_shift},
])

"""**Hypothesis 1: Mamba will be more robust than a Transformer when irrelevant filler text is inserted into the input, because Mamba's selective memory should learn to ingore unimportant tokens.**"""

import torch
import math
import random
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForCausalLM
from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel
from datasets import load_dataset

def add_irrelevant_filler(text, filler_ratio=0.1):
    filler_words = [
        "blahblah", "xyzxyz", "dummytext", "fillerword",
        "aaaaaaaaa", "bbbbbbbbb", "randomnoise", "irrelevant",
        "testtesttest", "placeholder", "voidvoid", "blankblank"
    ]
    words = text.split()
    if len(words) < 100:
        words = words * (100 // len(words) + 1)
    num_fillers = int(len(words) * filler_ratio)
    for _ in range(num_fillers):
        insert_pos = random.randint(0, len(words))
        words.insert(insert_pos, random.choice(filler_words))
    return " ".join(words)

dataset = load_dataset("wikitext", "wikitext-2-raw-v1", split="test")
long_texts = [text for text in dataset["text"] if len(text.strip()) > 100]
clean_text = "\n\n".join(long_texts[:10])

mamba_tokenizer = AutoTokenizer.from_pretrained("state-spaces/mamba-130m")
mamba_tokenizer.pad_token = mamba_tokenizer.eos_token
mamba_model = MambaLMHeadModel.from_pretrained("state-spaces/mamba-130m").cuda()

pythia_tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-160m")
pythia_tokenizer.pad_token = pythia_tokenizer.eos_token
pythia_model = AutoModelForCausalLM.from_pretrained("EleutherAI/pythia-160m").cuda()

def compute_ppl(model, tokenizer, text, max_len=1024, is_mamba=False):
    encoding = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=max_len,
        padding="max_length"
    )
    input_ids = encoding["input_ids"].cuda()
    if (input_ids[0] == tokenizer.pad_token_id).all():
        input_ids = torch.randint(100, 1000, (1, max_len), device="cuda")
    with torch.no_grad():
        if is_mamba:
            logits = model(input_ids).logits
            shift_logits = logits[..., :-1, :].contiguous()
            shift_labels = input_ids[..., 1:].contiguous()
            loss = F.cross_entropy(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
        else:
            outputs = model(input_ids, labels=input_ids)
            loss = outputs.loss
        ppl = math.exp(loss)
    return loss.item(), ppl

print("=" * 70)
print("Ablation Study 1: Irrelevant Filler Text Robustness Comparison")
print("=" * 70)

filler_ratios = [0.0, 0.1, 0.3, 0.5]
results = {"Mamba": [], "Pythia (Transformer)": []}

for ratio in filler_ratios:
    print(f"\n--- Filler Ratio: {int(ratio*100)}% ---")
    noisy_text = add_irrelevant_filler(clean_text, filler_ratio=ratio)
    mamba_loss, mamba_ppl = compute_ppl(mamba_model, mamba_tokenizer, noisy_text, is_mamba=True)
    results["Mamba"].append(mamba_ppl)
    pythia_loss, pythia_ppl = compute_ppl(pythia_model, pythia_tokenizer, noisy_text, is_mamba=False)
    results["Pythia (Transformer)"].append(pythia_ppl)

mamba_baseline = results["Mamba"][0]
pythia_baseline = results["Pythia (Transformer)"][0]

print("\n" + "=" * 70)
print("Final Results Summary (Relative to Baseline)")
print("=" * 70)
print(f"{'Filler Ratio':<12} | {'Mamba':<15} | {'Transformer':<15}")
print("-" * 70)
for i, ratio in enumerate(filler_ratios):
    mamba_change = results["Mamba"][i] / mamba_baseline
    pythia_change = results["Pythia (Transformer)"][i] / pythia_baseline

    mamba_str = f"{mamba_change:.2f}x"
    pythia_str = f"{pythia_change:.2f}x"

    if mamba_change < 1:
        mamba_str += f" (↓{((1-mamba_change)*100):.0f}%)"
    elif mamba_change > 1:
        mamba_str += f" (↑{((mamba_change-1)*100):.0f}%)"

    if pythia_change < 1:
        pythia_str += f" (↓{((1-pythia_change)*100):.0f}%)"
    elif pythia_change > 1:
        pythia_str += f" (↑{((pythia_change-1)*100):.0f}%)"

    print(f"{int(ratio*100):<12}% | {mamba_str:<15} | {pythia_str:<15}")
print("=" * 70)

print("\nHypothesis Validation:")
print("If Mamba's relative increase is significantly smaller than Transformer's → Hypothesis holds")

"""**Hypothesis 2: The combination of Selective Delta and Selective C will achieve lower perplexity than using only one of them or removing selectivity.**"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleSelectiveSSM(nn.Module):
    def __init__(self, d_model, d_state=16, selective_delta=True, selective_c=True):
        super().__init__()
        self.d_model = d_model
        self.d_state = d_state
        self.selective_delta = selective_delta
        self.selective_c = selective_c

        self.in_proj = nn.Linear(d_model, d_model)
        self.delta_proj = nn.Linear(d_model, d_model)
        self.c_proj = nn.Linear(d_model, d_model)
        self.fixed_delta = nn.Parameter(torch.zeros(d_model))
        self.fixed_c = nn.Parameter(torch.ones(d_model))
        self.out_proj = nn.Linear(d_model, d_model)

    def forward(self, x):
        batch, seq_len, d_model = x.shape
        u = torch.tanh(self.in_proj(x))
        if self.selective_delta:
            delta = torch.sigmoid(self.delta_proj(x))
        else:
            delta = torch.sigmoid(self.fixed_delta).view(1, 1, d_model)
            delta = delta.expand(batch, seq_len, d_model)

        if self.selective_c:
            c = torch.sigmoid(self.c_proj(x))
        else:
            c = torch.sigmoid(self.fixed_c).view(1, 1, d_model)
            c = c.expand(batch, seq_len, d_model)

        h = torch.zeros(batch, d_model, device=x.device)
        outputs = []

        for t in range(seq_len):
            h = (1 - delta[:, t, :]) * h + delta[:, t, :] * u[:, t, :]
            y = c[:, t, :] * h
            outputs.append(y.unsqueeze(1))

        y = torch.cat(outputs, dim=1)
        return self.out_proj(y)

class SimpleMambaLM(nn.Module):
    def __init__(self, vocab_size, d_model=128, n_layers=4,
                 selective_delta=True, selective_c=True):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, d_model)
        self.layers = nn.ModuleList([
            SimpleSelectiveSSM(
                d_model=d_model,
                selective_delta=selective_delta,
                selective_c=selective_c
            )
            for _ in range(n_layers)
        ])

        self.norm = nn.LayerNorm(d_model)
        self.lm_head = nn.Linear(d_model, vocab_size)

    def forward(self, input_ids, labels=None):
        x = self.embed(input_ids)
        for layer in self.layers:
            x = x + layer(x)
        x = self.norm(x)
        logits = self.lm_head(x)

        loss = None
        if labels is not None:
            shift_logits = logits[:, :-1, :].contiguous()
            shift_labels = labels[:, 1:].contiguous()
            loss = F.cross_entropy(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_labels.view(-1)
            )

        return {"loss": loss, "logits": logits}

vocab_size = len(tokenizer)

models = {
    "Full_Delta_C": SimpleMambaLM(
        vocab_size,
        selective_delta=True,
        selective_c=True
    ).cuda(),

    "Delta_only": SimpleMambaLM(
        vocab_size,
        selective_delta=True,
        selective_c=False
    ).cuda(),

    "C_only": SimpleMambaLM(
        vocab_size,
        selective_delta=False,
        selective_c=True
    ).cuda(),

    "No_Delta_No_C": SimpleMambaLM(
        vocab_size,
        selective_delta=False,
        selective_c=False
    ).cuda(),
}

import math

def evaluate_ppl(model, dataloader):
    model.eval()
    total_loss = 0
    total_tokens = 0

    with torch.no_grad():
        for batch in dataloader:
            input_ids = batch["input_ids"].cuda()
            labels = batch["labels"].cuda()

            outputs = model(input_ids, labels=labels)
            loss = outputs["loss"]

            num_tokens = labels[:, 1:].numel()
            total_loss += loss.item() * num_tokens
            total_tokens += num_tokens

    avg_loss = total_loss / total_tokens
    ppl = math.exp(avg_loss)
    return avg_loss, ppl

from torch.utils.data import DataLoader
def tokenize_fn(example):
    return tokenizer(example["text"], truncation=True)

tokenized_dataset = dataset.map(
    tokenize_fn,
    batched=True,
    remove_columns=["text"]
)
if "attention_mask" in tokenized_dataset["train"].column_names:
    tokenized_dataset = tokenized_dataset.remove_columns(["attention_mask"])

block_size = 128
def group_texts(examples):
    concatenated = sum(examples["input_ids"], [])
    total_length = len(concatenated)
    total_length = (total_length // block_size) * block_size
    input_ids = [
        concatenated[i:i + block_size]
        for i in range(0, total_length, block_size)
    ]

    return {
        "input_ids": input_ids,
        "labels": input_ids.copy()
    }

lm_dataset = tokenized_dataset.map(group_texts,
                                   batched=True,
                                   remove_columns=tokenized_dataset["train"].column_names)

def collate_fn(batch):
    return {
        "input_ids": torch.tensor([x["input_ids"] for x in batch], dtype=torch.long),
        "labels": torch.tensor([x["labels"] for x in batch], dtype=torch.long),
    }

small_train_dataset = lm_dataset["train"].select(range(min(500, len(lm_dataset["train"]))))
small_val_dataset = lm_dataset["test"].select(range(min(100, len(lm_dataset["test"]))))

train_dataloader = DataLoader(
    small_train_dataset,
    batch_size=4,
    shuffle=True,
    collate_fn=collate_fn
)

val_dataloader = DataLoader(
    lm_dataset["test"],
    batch_size=4,
    shuffle=False,
    collate_fn=collate_fn
)

def train_model(model, train_dataloader, num_steps=200, lr=1e-3):
    model.train()
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    step = 0
    train_losses = []
    while step < num_steps:
        for batch in train_dataloader:
            if step >= num_steps:
                break

            input_ids = batch["input_ids"].cuda()
            labels = batch["labels"].cuda()

            optimizer.zero_grad()

            outputs = model(input_ids, labels=labels)
            loss = outputs["loss"]
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())

            if step % 25 == 0:
                print(f"step {step}, loss = {loss.item():.4f}")
            step += 1
    return train_losses

import pandas as pd
variant_info = {
    "Full_Delta_C": {"Selective Delta": "Yes", "Selective C": "Yes"},
    "Delta_only": {"Selective Delta": "Yes", "Selective C": "No"},
    "C_only": {"Selective Delta": "No", "Selective C": "Yes"},
    "No_Delta_No_C": {"Selective Delta": "No", "Selective C": "No"},
}

results = []

for name, model in models.items():
    print(f"\nTraining {name}...")
    train_losses = train_model(
        model,
        train_dataloader,
        num_steps=200,
        lr=1e-3
    )
    print(f"Evaluating {name}...")
    avg_loss, ppl = evaluate_ppl(model, val_dataloader)
    results.append({
        "Model Variant": name,
        "Selective Delta": variant_info[name]["Selective Delta"],
        "Selective C": variant_info[name]["Selective C"],
        "Final Train Loss": train_losses[-1],
        "Validation Loss": avg_loss,
        "Perplexity": ppl
    })

results_df = pd.DataFrame(results)
results_df

import pandas as pd
results_df = pd.DataFrame(results)
results_df

"""**Extension for hypothesis 2: adding input sequences with different length to check if removing the selective mechanism will increase perplexity for long input sequences**"""

block_sizes = [64, 128, 256]
all_results = []

for block_size in block_sizes:
    print(f"\n============================")
    print(f"BLOCK SIZE = {block_size}")
    print(f"============================")

    def group_texts(examples):
        concatenated = sum(examples["input_ids"], [])
        total_length = len(concatenated)
        total_length = (total_length // block_size) * block_size

        input_ids = [
            concatenated[i:i + block_size]
            for i in range(0, total_length, block_size)
        ]

        return {
            "input_ids": input_ids,
            "labels": [x.copy() for x in input_ids]
        }

    lm_dataset = tokenized_dataset.map(
        group_texts,
        batched=True,
        remove_columns=tokenized_dataset["train"].column_names
    )

    small_train_dataset = lm_dataset["train"].select(
        range(min(500, len(lm_dataset["train"])))
    )
    small_val_dataset = lm_dataset["test"].select(
        range(min(100, len(lm_dataset["test"])))
    )

    train_dataloader = DataLoader(
        small_train_dataset,
        batch_size=4,
        shuffle=True,
        collate_fn=collate_fn
    )

    val_dataloader = DataLoader(
        small_val_dataset,
        batch_size=4,
        shuffle=False,
        collate_fn=collate_fn
    )
    vocab_size = len(tokenizer)

    models = {
        "Full_Delta_C": SimpleMambaLM(vocab_size, selective_delta=True, selective_c=True).cuda(),
        "Delta_only": SimpleMambaLM(vocab_size, selective_delta=True, selective_c=False).cuda(),
        "C_only": SimpleMambaLM(vocab_size, selective_delta=False, selective_c=True).cuda(),
        "No_Delta_No_C": SimpleMambaLM(vocab_size, selective_delta=False, selective_c=False).cuda(),
    }

    for name, model in models.items():
        print(f"\nTraining {name} (block={block_size})...")

        train_model(model, train_dataloader, num_steps=200, lr=1e-3)

        print(f"Evaluating {name}...")
        avg_loss, ppl = evaluate_ppl(model, val_dataloader)

        all_results.append({
            "Block Size": block_size,
            "Model Variant": name,
            "Selective Delta": variant_info[name]["Selective Delta"],
            "Selective C": variant_info[name]["Selective C"],
            "Validation Loss": avg_loss,
            "Perplexity": ppl
        })

results_df = pd.DataFrame(all_results)
results_df